// Google Sheets Proxy — Hikari Electrical & Automation
// Auto-generated by Rolebase build script

const SHEET_URL = ''

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end()
  try {
    const response = await fetch(SHEET_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(req.body),
      redirect: 'follow',
    })
    const text = await response.text()
    res.status(200).json({ ok: true, upstream: text })
  } catch (err) {
    console.error('Sheets proxy error:', err)
    res.status(500).json({ ok: false, error: err.message })
  }
}
