// GHL Contact Creator — Fiacon Cleaning Services
// Auto-generated by Rolebase build script

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end()

  const body = req.body || {}
  const GHL_TOKEN = process.env.GHL_TOKEN
  const LOCATION_ID = 'ujex7N3PBEdbRYHZVxAn'

  if (!GHL_TOKEN) return res.status(500).json({ error: 'No GHL token configured' })

  // Landing page posts the applicant's name as `name`
  const nameParts = (body.name || body.business_name || '').trim().split(' ')
  const firstName = nameParts[0] || ''
  const lastName = nameParts.slice(1).join(' ') || ''

  try {
    const contactRes = await fetch('https://services.leadconnectorhq.com/contacts/', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${GHL_TOKEN}`,
        'Version': '2021-07-28',
      },
      body: JSON.stringify({
        locationId: LOCATION_ID,
        firstName,
        lastName,
        phone: body.phone,
        email: body.email,
        tags: ['hiring-funnel'],
        source: 'Fiacon Cleaning Services Hiring Page',
        customFields: [

        ],
      }),
    })

    const data = await contactRes.json()
    res.status(200).json({ ok: true, contactId: data?.contact?.id })
  } catch (err) {
    console.error('GHL error:', err)
    res.status(500).json({ error: err.message })
  }
}
